name: Lint

on: [push, pull_request]

jobs:
  Lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Check Readmes
        run: |
          bash ./.github/scripts/check_for_missing_readme_md.sh
